export const themeCustom = {
  token: {
    colorPrimary: '#4979D1',
    borderRadius: 5,
    controlHeight: 26,
    FontSizeOutlined: 9,
    lightSiderBg: 'rgba(0, 57, 114, 0.90)',
    fontSize: 10,
    padding: 10,
    paddingLG: 10,
  },
  components: {
    Input: {
      inputFontSizeLG: 10,
      inputFontSize: 10,
      inputFontSizeSM: 10,
      paddingBlockLG: 4,
      paddingInline: 11,
      paddingBlock: 3,
    },
    Form: {
      labelFontSize: 10,
      labelHeight: 14,
      labelColor: '#003972',
      itemMarginBottom: 8,
      verticalLabelPadding: '0 0 4px',
    },
    Select: {
      optionFontSize: 10,
      optionHeight: 20,
      optionPadding: '5px 10px',
      showArrowPaddingInlineEnd: 20,
      multipleItemHeightLG: 20,
      multipleItemHeightSM: 20,
      multipleItemHeight: 20,
      singleItemHeightLG: 20,
    },
    Modal: {
      titleFontSize: 13,
      padding: 10,
      borderRadius: 10,
    },
    Menu: {
      collapsedWidth: 100,
    },
    Pagination: { itemSize: 25 },
    Table: {
      headerBg: '#E1EBF5',
      headerColor: '#003972',
      headerBorderRadius: 5,
      cellFontSize: 9,
      cellPaddingBlock: 8,
      rowHoverBg: 'rgba(0, 90, 180, 0.1)',
    },
    Radio: {
      dotSize: 8,
      buttonSolidCheckedActiveBg: '#597ef7',
      buttonSolidCheckedBg: '#597ef7',
      buttonSolidCheckedHoverBg: '#597ef7',
      buttonPaddingInline: 0,
    },
    // Tabs: {
    //   horizontalItemPadding: 6,
    //   horizontalMargin: '0 0 10px 0',
    //   horizontalItemGutter: 10,
    // },
    // Transfer: {
    //   listWidth: 300,
    //   listHeight: 250,
    // },
    Tabs: {
      cardPaddingLG: '4px 24px',
      titleFontSizeLG: 11,
      horizontalMargin: '0 0 0 0',
    },
    List: {
      itemPaddingSM: '8px 8px',
      itemPadding: '8px 0',
    },
    Collapse: {
      headerBg: '#E1EBF5',
      headerPadding: '4px 6px',
      contentPadding: '0 0',
    },
  },
};
